server:
  port: 8083
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: discovery-client-feign-service
              uri: lb://DISCOVERY-CLIENT-FEIGN-SERVICE
              predicates:
                - Path=/user/*
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 2   # 5 requests per second
                    redis-rate-limiter.burstCapacity: 2  # max burst of 10
                - name: CircuitBreaker
                  args:
                    name: userServiceCB
                    fallbackUri: forward:/fallback
                    key-resolver: "#{@ipKeyResolver}"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0  # traces 100% of requests
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
